# Generated by Django 4.1 on 2023-01-04 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("credentials", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("district", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ProcessData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("dob", models.DateField()),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=250)),
                ("phone", models.IntegerField()),
                ("email", models.EmailField(max_length=250)),
                ("address", models.CharField(max_length=250)),
                ("acctype", models.CharField(max_length=250)),
                ("matpro", models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(name="Place",),
        migrations.AddField(
            model_name="branch",
            name="distid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="credentials.district"
            ),
        ),
    ]
