# Generated by Django 4.1.4 on 2022-12-30 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bankapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Place",),
    ]
